components:
  schemas:
    Seller:
      type: object
      properties:
        names:
          type: string
          example: "Juan Carlos"
        lastNames:
          type: string
          example: "Pérez García"
        numberID:
          type: number
          example: 1234567890
        email:
          type: string
          example: "juan.perez@empresa.com"
        username:
          type: string
          example: "jperez2024"
        password:
          type: string
          example: "Contraseña123*"
        SalesCity:
          type: string
          example: "Quito"
        PhoneNumber:
          type: number
          example: 0987654321
        role:
          type: string
          example: "seller"
        status:
          type: boolean
          example: true
        token:
          type: string
          example: "abc123def456"
        confirmEmail:
          type: boolean
          example: false

paths:
  /api/login:
    post:
      tags:
        - Vendedores
      summary: Login vendedor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "jperez2024"
                password:
                  type: string
                  example: "Contraseña123*"
      responses:
        200:
          description: Login exitoso
          content:
            application/json:
              schema:
                type: object
                example:
                  msg: "Inicio de sesión exitoso"
                  tokenJWT: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        400:
          description: Error en credenciales
          content:
            application/json:
              schema:
                type: object
                examples:
                  datosIncompletos:
                    value:
                      msg: "Faltan datos por ingresar"
                  emailNoConfirmado:
                    value:
                      msg: "Lo sentimos primero debes confirmar tu email"
                  usuarioNoEncontrado:
                    value:
                      msg: "Usuario no encontrado"
                  contraseñaIncorrecta:
                    value:
                      msg: "Contraseña incorrecta"

  /api/confirm-account/{token}:
    get:
      tags:
        - Vendedores
      summary: Confirmar cuenta de vendedor
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          example: "abc123def456"
      responses:
        200:
          description: Cuenta confirmada
          content:
            application/json:
              schema:
                type: object
                example:
                  msg: "Token confirmado, ya puedes iniciar sesión"
        400:
          description: Error en confirmación
          content:
            application/json:
              schema:
                type: object
                example:
                  msg: "Lo sentimos no se puede validar la cuenta"

  /api/recovery-password:
    post:
      tags:
        - Vendedores
      summary: Solicitar recuperación de contraseña
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "juan.perez@empresa.com"
      responses:
        200:
          description: Email de recuperación enviado
          content:
            application/json:
              schema:
                type: object
                example:
                  msg: "Se ha enviado un correo para recuperar la contraseña"
        400:
          description: Error en solicitud
          content:
            application/json:
              schema:
                type: object
                examples:
                  datosIncompletos:
                    value:
                      msg: "Faltan datos por ingresar"
                  usuarioNoEncontrado:
                    value:
                      msg: "Usuario no encontrado"

  /api/recovery-password/{token}:
    get:
      tags:
        - Vendedores
      summary: Verificar token de recuperación
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          example: "abc123def456"
      responses:
        200:
          description: Token verificado
          content:
            application/json:
              schema:
                type: object
                example:
                  msg: "Token confirmado, ya puedes crear una nueva contraseña"
        400:
          description: Error en verificación
          content:
            application/json:
              schema:
                type: object
                example:
                  msg: "Lo sentimos, no se puede validar la cuenta"

    post:
      tags:
        - Vendedores
      summary: Establecer nueva contraseña
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          example: "abc123def456"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: "NuevaContraseña123*"
                confirmpassword:
                  type: string
                  example: "NuevaContraseña123*"
      responses:
        200:
          description: Contraseña actualizada
          content:
            application/json:
              schema:
                type: object
                example:
                  msg: "Cambio de contraseña correctamente"
        400:
          description: Error en actualización
          content:
            application/json:
              schema:
                type: object
                examples:
                  camposVacios:
                    value:
                      msg: "Lo sentimos debes llenar todos los campos"
                  contraseñasNoCoinciden:
                    value:
                      msg: "Las contraseñas no coinciden"
                  emailNoConfirmado:
                    value:
                      msg: "Lo sentimos primero debes confirmar tu email"